### ISSUE TITLE
linking issue with openmpi on arch linux (blt_mpi_smoke fails to link)

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#331]
reported by an ascent user, encountered  in conduit build. 

Is likely a cmake issue,  not a blt issue per se.

gcc 9.2.0 on arch linux
spack built openmpi-3.1.4
BLT Version: 0.2.5
CMake Version: 3.14.5

```
[  6%] Linking CXX executable ../../../tests/blt_mpi_smoke
cd BUILD_LOC/spack/var/spack/stage/spack-stage-conduit-master-kxqo2mlz4yzti5ougeq2m2fhlzaa73be/spack-src/spack-build/blt/tests/smoke && BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/cmake-3.14.5-wcfeiamw55g4vwlceklvxyibctne2lgb/bin/cmake -E cmake_link_script CMakeFiles/blt_mpi_smoke.dir/link.txt --verbose=1
/usr/bin/g++      -O2 -g -DNDEBUG  -rdynamic 
-Wl,-rpath -Wl,BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/hwloc-1.11.11-ljswr5og475ralakqrelzykauwnfw3lf/lib 
-Wl,BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib 
-LBUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/hwloc-1.11.11-ljswr5og475ralakqrelzykauwnfw3lf/lib 
-pthread 
CMakeFiles/blt_mpi_smoke.dir/blt_mpi_smoke.cpp.o  
-o ../../../tests/blt_mpi_smoke 
-Wl,-rpath,BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib 
BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib/libmpi.so 
BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib/libmpi_cxx.so 
BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib/libmpi_usempif08.so 
BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib/libmpi_usempi_ignore_tkr.so 
BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib/libmpi_mpifh.so 
```

Error:
`ld: BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib: file not recognized: Is a directory
`
Looks like a malformed rpath command, the linker is simply passed a directory:

`-Wl,BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib
`
Notice later it is also passed what looks like the expected rpath command:

` -Wl,-rpath,BUILD_LOC/spack/opt/spack/linux-arch-sandybridge/gcc-9.2.0/openmpi-3.1.4-7tuxmnjnzj5swmus2shzh3jep2prtzuv/lib`

**Comment by mclarsen** [comment]
also reported by me.

**Comment by kennyweiss** [comment]
`v0.2.5` is fairly old and @white238 had several bugfixes for MPI-related flags.

Any chance this has been resolved in newer versions of `blt`?

**Comment by cyrush** [comment]
I recalled there were some changes + recommend Matt update and I don't think that resolved the problem.

I suspect the openmpi compiler wrapper `showme` is feeding bad link lines to CMake, and those might be hard, but not impossible to tactically fix. 

Usually when folks hit his problem, we tell them to use mpich, end of story.

In our new case, we need openmpi since there is some container magic at play that requires it.

**Comment by white238** [comment]
Can you post the BLT MPI Info that CMake reports during the CMake phase? or have the openmpi installed somewhere I can run BLT against?

**Comment by cyrush** [comment]
I am going to try to look into this this afternoon

**Comment by mclarsen** [comment]
I tried with the head of develop and it was still an issue. This issue I had was `cmake 3.14.5 + openmi@4.0.3` and I think this happens with some 3.x versions of openmpi as well.

**Comment by mclarsen** [comment]
Here are the link flags reported by BLT:

```
BLT MPI Link Flags:     -Wl,-rpath,/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/gcc-6.4.0-yhjjnaihh4ncvwvzzvaaubvpsv6bs7b7/lib/gcc/powerpc64le-unknown-linux-gnu/6.4.0 -Wl,-rpath,/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/gcc-6.4.0-yhjjnaihh4ncvwvzzvaaubvpsv6bs7b7/lib64 -Wl,-rpath -Wl,/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/hwloc-1.11.11-aog7wq2ihc6om5wgg45hehwqzwiiillm/lib -Wl,-rpath -Wl,/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/zlib-1.2.11-e2b4wdtai7bc2bnjar3ga3isjabs2pml/lib -Wl,-rpath -Wl,/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/openmpi-4.0.3-u44cjrpsmamobvv7w7dfdnmjcgu3ctlg/lib -L/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/hwloc-1.11.11-aog7wq2ihc6om5wgg45hehwqzwiiillm/lib -L/spack/opt/spack/linux-rhel7-power9le/gcc-6.4.0/zlib-1.2.11-e2b4wdtai7bc2bnjar3ga3isjabs2pml/lib -pthread
```

**Comment by cyrush** [comment]
even better: cmake 3.10 works fine, so this involves recent changes to the FindMPI logic in cmake.

**Comment by cyrush** [comment]
show me from version of openmpi that causes this:

```
user@acca17165a1e:~/blt/docs/tutorial/calc_pi/build$ mpicc --showme
/usr/bin/gcc -I/home/user/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/openmpi-3.1.6-pzmebw34oh7bifr6pu4fjxfqeoje2o5d/include -pthread -L/home/user/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/hwloc-1.11.11-fl4w6luvijw4llh7ra4d7g6tj5u4lwce/lib -L/home/user/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/zlib-1.2.11-zkl5ufya6sj7wsnrqkcqbgnay3byre7h/lib -Wl,-rpath -Wl,/home/user/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/hwloc-1.11.11-fl4w6luvijw4llh7ra4d7g6tj5u4lwce/lib -Wl,-rpath -Wl,/home/user/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/zlib-1.2.11-zkl5ufya6sj7wsnrqkcqbgnay3byre7h/lib -Wl,-rpath -Wl,/home/user/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/openmpi-3.1.6-pzmebw34oh7bifr6pu4fjxfqeoje2o5d/lib -L/home/user/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/openmpi-3.1.6-pzmebw34oh7bifr6pu4fjxfqeoje2o5d/lib -lmpi
```

**Comment by rhornung67** [comment]
> even better: cmake 3.10 works fine, so this involves recent changes to the FindMPI logic in cmake.

I thought @white238 was the person who fought to make cmake 3.14.5 the default on all LC systems.... 🤣

**Comment by cyrush** [comment]
Well we need 3.14.x for other reasons.  And not 3.15 or 3.16 for reasons, and now not 3.18 for reasons. 

https://en.wikipedia.org/wiki/Whac-A-Mole

Reasons control our destiny.

**Comment by rhornung67** [comment]
https://en.wikipedia.org/wiki/Facebuster

**Comment by gzagaris** [comment]
> Well we need 3.14.x for other reasons. And not 3.15 or 3.16 for reasons, and now not 3.18 for reasons.
> 
> https://en.wikipedia.org/wiki/Whac-A-Mole
> 
> Reasons control our destiny.

That's really great -- projects like VTK keep patches for different CMake versions: 
- https://github.com/Kitware/VTK/tree/master/CMake/patches
- https://github.com/Kitware/VTK/tree/master/CMake/patches/3.17

I am not really advocating that we do that, just thought it would be good to know...

**Comment by cyrush** [comment]
I am hoping we have a path to defend against this in BLT but need to sink some more time to see what is possible.

Could also use/distribute a modified FindMPI in BLT, but that has downsides (Like when we had to fix gaps with CUDA support)
Spack patches are another option, but won't help everywhere. 
Fixing in CMake also a good longer term option.

**Comment by cyrush** [comment]
problem is related to de-dup of linking strings which strips the 3rd, 4th, and 5th rpath command.

**Comment by mclarsen** [comment]
Btw, I just got another email from someone else who just hit this.

**Comment by cyrush** [comment]
I found the issue. 

for cmake 3.13+ we use `LINK_OPTIONS` instead of `LINK_FLAGS`.  ( https://cmake.org/cmake/help/git-stage/command/target_link_options.html)

We are trying to use `SHELL:` to avoid de-duping -- which `LINK_OPTIONS` does for us as a service, however we aren't quite doing it right. 

In our current usage:
https://github.com/LLNL/blt/blob/095becb5af6af5c2a2290d2fbcb5246cc01e7345/cmake/BLTMacros.cmake#L266

Since we have a list, `SHELL:` will only apply to the first entry of the list. Then we get one more rpath in there for good measure, and the rest are eaten. This explains why 2 survive, and the next 3 are gone. Leaving all the blame on zlib, which isn't at all responsible for the tragedy. 

To use `SHELL:` correctly, I think the entire set of flags needs to be one string with the `SHELL:` prefix. 
I tested this and that works. 

That said, I feel like this also might stop generator expressions, which was the reason for using the  the newer `LINK_OPTIONS` magic in the first place.?

I also tested our old path (pre 3.13), which uses `LINK_FLAGS` and that works fine. I expected that was the case, as CMake 3.10 works. 

So what should we do? How important are generator expressions in our linking flags?

**Comment by cyrush** [comment]
I can make an MPI only fix pretty easily, by passing a string that includes the shell command prefix when we do a register library. 

But this issue is evil, I don't want someone else to trip over it in a more general case.

**Comment by white238** [comment]
You dont have an option to use LINK_FLAGS vs LINK_OPTIONS in 3.13+, it was removed.  It did give us the use of generator expressions (a generally mixed bag), but it also changes this from a string to a list, which is the source of a lot of problems.

As for this specific issue, I think just doing SHELL:<the whole string> is probably the way to go.  Especially since this is coming out of the mpi wrapper and won't have generator expressions.  As long as you are adding it to the non-user overridden variable.

**Comment by cyrush** [comment]
hmm, well i changed to:

`if( ${CMAKE_VERSION} VERSION_GREATER_EQUAL "4.13.0" )`

which triggers our old logic that sets the LINK_FLAGS, and the expected flags show up during linking?

**Comment by cyrush** [comment]
old path uses the generic set target props.

For now, I think the right path is to fix for mpi, i'll do that.
